"""add nested entities AccessGrant

Revision ID: c30e72ee7757
Revises: a6cf1d6dd1de
Create Date: 2026-09-16 14:48:12.607374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c30e72ee7757'
down_revision: Union[str, Sequence[str], None] = 'a6cf1d6dd1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_grant',
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.ARRAY(sa.Enum('ACCESS', 'EXECUTE', 'EXPORT', 'COMMENT', 'AUDIT', name='accesstype')), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='accessstatus'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(
        sa.text(
            "UPDATE users "
            "SET deleted_at = now() "
            "WHERE is_deleted = TRUE"
        )
    )
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
    )
    op.execute(
        sa.text(
            "UPDATE users "
            "SET is_deleted = deleted_at IS NOT NULL"
        )
    )
    op.alter_column('users', 'is_deleted', nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'deleted_at')
    op.drop_table('access_grant')
    bind = op.get_bind()
    sa.Enum(name='accessstatus').drop(bind, checkfirst=True)
    sa.Enum(name='accesstype').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
