"""add access grants

Revision ID: fae7c79c4c24
Revises: a6cf1d6dd1de
Create Date: 2026-09-10 07:42:50.672976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae7c79c4c24'
down_revision: Union[str, Sequence[str], None] = 'a6cf1d6dd1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_grant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.ARRAY(sa.Enum('ACCESS', 'EXECUTE', 'EXPORT', 'COMMENT', 'AUDIT', name='accesstype')), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='accessstatus'), nullable=False),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_grant')
    # ### end Alembic commands ###
